# Site settings
title: Solace Samples Template
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-template" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-template
